version: '3.7'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./history_wall_api:/var/www/html
    ports:
      - "9000:9000"
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql
    ports:
      - "4306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my_conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./history_wall_api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
